config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
  	resources :comments
  end

  get 'home/index'
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts
	has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :confirmable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :find_post
	before_action :find_comment, only: [:edit, :update, :destroy]
	before_action :authenticate_user!

	def new
		
	end

	def create
		@comment = @post.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @comment.update(comment_params)
			redirect_to post_path(@post)
		else
			render edit
		end
	end

	def destroy
		@comment.destroy
		redirect_to post_path(@post)
	end

	private
		def comment_params
			params.require(:comment).permit(:content)
		end

		def find_post
			@post = Post.find(params[:post_id])
		end

		def find_comment
			@comment = @post.comments.find(params[:id])
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_params, only:[:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def show
		
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @post.update(post_params)
			redirect_to post_path
		else
			render 'new'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

		def post_params
			params.require(:post).permit(:title, :body)
		end

		def find_params
			@post = Post.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<p class="comment-content"><%= auto_link(comment.content) %></p>
	<p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>
	<div class="links">
		<% if user_signed_in? %>
			<% if comment.user_id == current_user.id %>
				<%= link_to "Edit Comment", edit_post_comment_path(comment.post, comment), class: "btn btn-default" %>
				<%= link_to "Delete Comment", post_comment_path(comment.post, comment), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
				<br />
			<% end %>
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
	<%= f.input :content, label: "Comment" %>
	<%= f.button :submit, :class => "btn-custom" %>
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>
<%= simple_form_for([@post, @comment]) do |f| %>
	<%= f.input :content, label: "Comment" %>
	<%= f.button :submit %>
<% end %>

app/views/home/index.html.erb
<h1>Homepage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "Blitz Board", root_path, class: "navbar-brand" %>
			</div>
			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
				<% else %>
					<li><%= link_to "Log	 In", new_user_session_path %></li>
				<% end %>
			</ul>
			<% if user_signed_in? %>
				<p><%= link_to "Create new post", new_post_path, class: "navbar-right navbar-text navbar-link btn btn-default" %></p>
			<% end %>
		</div>
	</div>


	<% flash.each do |key, value| %>
	    <div class="alert alert-<%= key %> alert-dismissable">
	        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	        <%= value %>
	    </div>
	<% end %>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title, label: "Title" %>
  <%= f.input :body, label: "Content" %>
  <%= f.button :submit %>
<% end %>

  

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="col-md-4">
	<div class="message">
		<h3 class="message-title"><%= post.title %></h3>
		<%= link_to "View post", post_path(post), class: "btn custom" %>
	</div>
</div>
<% end %>

app/views/posts/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h2>New Post</h2>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<h1><%= @post.title %></h1> 
		<p class="message-posted-by">Posted by <%= @post.user.email %> <%= time_ago_in_words(@post.created_at) %> ago</p>
		<p class="message-desc"><%= auto_link(@post.body) %></p>
		<br />
		<div class="links btn-group">
				<%= link_to "Back to Posts", posts_path, class: "btn btn-default" %>
			<% if user_signed_in? %>
				<% if @post.user_id == current_user.id %>
					<%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-default" %>
					<%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
				<% end %>
			<% end %>
		</div>
		<h3 class="relpy-to-msg">Comments</h3>
		<%= render @post.comments %>
		<br />
		<h3>Reply to Post:</h3>
		<%= render 'comments/form' %>
		<br />

	</div>

			